#!/bin/bash
#SBATCH --nodes=1
#SBATCH --time=08:00:00
#SBATCH --partition gpu_a100
#SBATCH --gpus 1
#SBATCH --output=slurm-pcma-angle.out
#SBATCH --error=slurm-pcma-angle.err

# Default to 'classical' if no mode is provided
MODE=${1:-quantum}

# load environment
module purge
module load 2024
module load Python/3.12.3-GCCcore-13.3.0
source venv/bin/activate

# execution script
python src/train.py --config configs/config.yaml --mode $MODE
